---
on: 
  workflow_dispatch:

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: repo-name
        run:   echo "$REPO_NAME"
        shell: bash
        env:
          REPO_NAME: ${{ github.event.repository.name }}
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
